---
engine: knitr #added as otherwise inline r code does not execute
---

# Beliefs problems

## Soccer

Your favourite soccer team is a terrible team that rarely wins. You know the following about your team:

- 5% of the time they win.
- When they win, they score at least two goals 60% of the time.
- When they lose, they score at least two goals 20% of the time.

a\) You hear that they scored at least two goals in their most recent game. Use Bayes' rule to calculate the probability that they won.

::: {.callout-tip collapse="true"}
## Answer

To answer this question, we need to use Bayes' rule.

```{=tex}
\begin{align*}
P(\text{win}|\text{2 goals})&=\frac{P(\text{2 goals}|\text{win})P(\text{win})}{P(\text{2 goals})} \\[12pt]
&=\frac{P(\text{2 goals}|\text{win})P(\text{win})}{P(\text{2 goals}|\text{win})P(\text{win})+P(\text{2 goals}|\text{lose})P(\text{lose})} \\[12pt]
&=\frac{0.6\times 0.05}{0.6\times 0.05+0.2\times 0.95} \\[12pt]
&=`r WP <- round((0.6*0.05)/(0.6*0.05+0.2*0.95), 3); WP`
\end{align*}
```

The team won with  `r round(WP*100, 1)`% probability.

:::

b\) Use natural frequencies to calculate the probability that they won.

::: {.callout-tip collapse="true"}
## Answer

Suppose there are 100 games.

That would mean there are 5 wins and 95 losses.

In those five wins, they would score at least two goals in three of them.

In the 95 losses, they would score at least two goals in $0.2\times 95=19$ of them.

That means 3 of the $3+19=22$ games in which they score two goals are wins.

Therefore:

\begin{align*}
P(\text{win}|\text{2 goals})&=\frac{\text{wins when they score two goals}}{\text{games where they score two goals}} \\[12pt]
&=\frac{3}{22} \\[12pt]
&=`r round(3/22*100, 1)`\%
\end{align*}

:::

## Roulette

Imagine you are in a casino and observing a roulette wheel. The last five spins of the wheel have all resulted in the ball landing on a red number. Now, the wheel is about to spin again.

a\) What is the probability that the next spin will be black?

::: {.callout-tip collapse="true"}
## Answer

The probability that the next spin will be black is ~50%. Each spin is independent of the previous spin. (Technically, the probability is slightly less than 50% because of the presence of the green 0 and, in the case of American roulette wheels, 00. I've ignored this for simplicity.)

:::

b\) Tommy is watching the same game of roulette. He suffers from the gambler's fallacy. What is he likely to believe? Give a potential explanation for his belief.

::: {.callout-tip collapse="true"}
## Answer

Tom is likely to believe that the next spin will be black. As he has the gambler’s fallacy, he will believe that an outcome not recently realised in a sequence of independent draws - in this case, black - is more likely to occur on the next draw.

:::

c\) Sammy is at the next table watching a game of craps. He has seen a player win by rolling 7 three times in a row. The player makes the same bet and is about to roll again. Sammy suffers from the hot hand fallacy. What is he likely to believe? Why?

::: {.callout-tip collapse="true"}
## Answer

Sammy is likely to believe that the next roll will be a 7. As he has the hot hand fallacy, he believes the streak will persist despite each outcome being independent of the last.

:::

## Buying a business

Dylan is considering buying a small business. The selling agent tells Dylan that the business is worth \$1.5 million. Dylan knows that the business is not worth that much.

a\) Use concepts from the material on beliefs to explain why an agent might tell Dylan the business is worth so much.

::: {.callout-tip collapse="true"}
## Answer

The agent is likely attempting to create an anchor. If Dylan uses the anchoring and adjustment heuristic in determining the price, he will start from that anchor and then inadequately adjust downwards. So despite knowing it is too high, it may still bias his estimate up.

:::

b\) To determine the value of the business, you estimate the revenue and profit the business will generate.  Dylan accounts for his belief that he will be able to increase the revenue substantially from current levels. He determines a fair valuation is \$1.1 million.

He purchases the business. However, after running the business for several months, he does not realise the profit he anticipated.

What form of overconfidence is this? Explain. Under what conditions does this form of overconfidence tend to emerge?


::: {.callout-tip collapse="true"}
## Answer

Dylan suffers from *overestimation*. Overestimation is the belief that we can perform at a level beyond that which we realistically can. In this case, Dylan did not generate the profit that he believed he could.

People typically overestimate when attempting a difficult task.

:::

c\) When developing his valuation, Dylan determined there was a 95% probability that the business was worth between \$1.08 million and \$1.12 million.

The business ultimately sold for \$1 million.

What form of overconfidence is this? Explain.

::: {.callout-tip collapse="true"}
## Answer

Dylan suffers from *overprecision*. Overprecision is the tendency to believe that our predictions or estimates are more accurate than they are. Dylan's overprecision is indicated by the narrow confidence interval he gave for the value of the business.

:::

## A loaded dice

You have two six-sided dice.

- One die is fair with the numbers 1 through to 6 occurring with equal probability.

- The other die is loaded and always rolls an even number. It rolls a 2, 4 or 6 with equal probability.

You pull one die out of your pocket and roll it. You did not check which die it was before you rolled. (Assume you could have pulled either die out of your pocket with equal probability.)

a\) The die shows a six. What is the probability that it is the loaded die? Calculate your answer using Bayes' rule.

```{=tex}
\begin{align*}
P(\text{D1 loaded}|6)&=\frac{P(6|\text{D1 loaded})P(\text{D1 loaded})}{P(6)} \\[6pt]
&=\frac{P(6|\text{D1 loaded})P(\text{D1 loaded})}{P(6|\text{D1 loaded})P(\text{D1 loaded})+P(6|\text{D1 fair})P(\text{D1 fair})} \\[6pt]
&=\frac{\frac{1}{3}\times 0.5}{\frac{1}{3}\times 0.5+\frac{1}{6}\times 0.5} \\[6pt]
&=`r PL<-(1/3*0.5)/(1/3*0.5+1/6*0.5); round(PL, 2)`
\end{align*}
```

The first die is the loaded die with `r round(PL*100, 1)`% probability.

b\) You pull the other die out of your pocket and roll it. It shows a 5. What is the updated probability that the first die you pulled out of your pocket is the loaded die? Calculate your answer using Bayes' rule.

```{=tex}
\begin{align*}
P(\text{D2 fair}|5)&=\frac{P(5|\text{D2 fair})P(\text{D2 fair})}{P(5)} \\[6pt]
&=\frac{P(5|\text{D2 fair})P(\text{D2 fair})}{P(5|\text{D2 fair})P(\text{D2 fair})+P(5|\text{D2 loaded})P(\text{D2 loaded})} \\[6pt]
&=\frac{\frac{1}{6}\times \frac{2}{3}}{\frac{1}{6}\times \frac{2}{3}+0\times \frac{1}{3}} \\[6pt]
&=`r (1/6*02/3)/(1/6*2/3+0*0.25)`
\end{align*}
```

The first die is the loaded die with 100% probability. This should make intuitive sense. The second die showed a 5 and is, therefore, fair with 100% probability. The loaded die never shows a 5.

