# Preferences

Economists use the preference relation to capture the ordering that an agent gives to options between which they might choose. There are three forms of the preference relation.

The first is the strong (or strict) preference relation. We use the strong preference relation to indicate that an agent considers one option "better than" another. We represent strong preference with the symbol $\succ$.

The second is the weak preference relation. We use the weak preference relation to indicate that an agent considers one option to be "at least as good as" another. We represent weak preference with the symbol $\succcurlyeq$.

The third is indifference. Indifference occurs where an agent considers that each option is "as good as" the other or that the the agent is "indifferent between" the options. We represent indifference with the symbol $\sim$.

Here are a couple of illustrations of these relations.

Suppose I strongly prefer bananas to apples. I would write my preference as:

- bananas $\succ$ apples

Similarly, if I am indifferent between bananas and oranges I would write:

- bananas $\sim$ oranges

There is an important link between indifference and the weak preference relation. $x \sim y$ if and only if $x \succcurlyeq y$ and $y \succcurlyeq x$. The weak preference relation includes the possibility of indifference.

In that case of my example of my indifference between oranges and bananas, I could also say that:

- bananas $\succcurlyeq$ oranges and oranges $\succcurlyeq$ bananas
