# Subjective expected utility theory

## Summary {.unnumbered}

- Subjective expected utility theory applies to situations of uncertainty where probabilities are unknown.
- Agents maximize subjective expected utility, $\mathbb{E}[U(X)]$, using subjective probabilities $\pi(x_i)$ for each outcome.
- Subjective probabilities typically comply with Bayesian probability theory, with decision-makers assumed to have beliefs consistent with Bayes' rule.
- The equation for subjective utility theory is similar to expected utility theory, but with subjective probabilities:

$$
\mathbb{E}[U(x)] = \sum_{i=1}^n \pi(x_i)u(x_i)
$$

---

::: {.content-visible when-format="html"}

{{< video https://youtu.be/5TIR4oL1Ors >}}

---

:::

Subjective expected utility theory is used in situations of uncertainty, where the probabilities are not known. People maximize expected utility using a subjective estimate of probability.

The agent maximises subjective expected utility, $\mathbb{E}[U(X)]$, using a subjective probability $\pi(x_i)$ for each outcome $x_i$.

While people may have different beliefs about the probabilities of different outcomes, as the word "subjective" indicates, these are typically assumed to comply with Bayesian probability theory. Decision makers are Bayesian, in that, given the evidence, they have beliefs that are consistent with Bayes' rule. I discuss Bayes' rule in more detail later.

The equation for subjective utility theory is the same as that for expected utility theory, except that the probabilities are subjective.

\begin{align*}
\mathbb{E}[U(X)]&=\pi(x_1)u(x_1)+\pi(x_2)u(x_2)+...+\pi(x_n)u(x_n)\\[6pt]
&=\sum_{i=1}^n \pi(x_i)u(x_i)
\end{align*}

You can think of this formula as comprising the following steps:

1. Define utility $u(x_i)$ over final outcomes $x_1,...,x_n$.

2. Define subjective probability $\pi(x_i)$ over final outcomes $x_1,...,x_n$.

3. Weight the utility of each outcome $u(x_i)$ by the subjective probability $\pi(x_i)$.

4. Add the weighted utilities.
