project:
  type: book

book:
  title: "Notes on behavioural economics"
  site-url: https://behaviouraleconomics.jasoncollins.blog
  author: "Jason Collins"
  date: "24 March 2023"
  date-format: D MMMM YYYY
  chapters:
    - index.qmd
    - part: foundations/economic-foundations.qmd
      chapters:
        - foundations/preferences.qmd
        - foundations/rationality.qmd
        - foundations/utility.qmd
        - foundations/economic-foundation-exercises.qmd
    - part: risk-and-uncertainty/decision-making-under-risk-and-uncertainty.qmd
      chapters:
        - risk-and-uncertainty/notation.qmd
        - risk-and-uncertainty/expected-value.qmd
        - risk-and-uncertainty/axioms-for-expected-utility-theory.qmd
        - risk-and-uncertainty/expected-utility-theory.qmd
        - risk-and-uncertainty/subjective-expected-utility.qmd
        - risk-and-uncertainty/expected-utility-examples.qmd
        - risk-and-uncertainty/anomalies-of-expected-utility-theory.qmd
        - risk-and-uncertainty/risk-and-uncertainty-exercises.qmd
    - part: prospect-theory/prospect-theory.qmd
      chapters:
        - prospect-theory/reference-dependence.qmd
        - prospect-theory/loss-aversion.qmd
        - prospect-theory/reflection-effect.qmd
        - prospect-theory/value-function.qmd
        - prospect-theory/probability-weighting.qmd
        - prospect-theory/prospect-theory-implementation.qmd
        - prospect-theory/prospect-theory-examples.qmd
        - prospect-theory/prospect-theory-applications.qmd
        - prospect-theory/prospect-theory-exercises.qmd
    - part: intertemporal-choice/intertemporal-choice.qmd
      chapters:
        - intertemporal-choice/exponential-discounting.qmd
        - intertemporal-choice/exponential-discounting-examples.qmd
        - intertemporal-choice/exponential-discounting-anomalies.qmd
        - intertemporal-choice/present-bias.qmd
        - intertemporal-choice/present-bias-examples.qmd
        - intertemporal-choice/sophisticated-present-bias.qmd
        - intertemporal-choice/commitment.qmd
        - intertemporal-choice/preference-over-profiles.qmd
        - intertemporal-choice/intertemporal-choice-applications.qmd
        - intertemporal-choice/intertemporal-choice-exercises.qmd
    - part: beliefs/beliefs.qmd
      chapters: 
        - beliefs/probability-foundations.qmd
        - beliefs/heuristics.qmd
        - beliefs/biases-in-probability-judgment.qmd
        - beliefs/heuristics-and-the-bias-variance-trade-off.qmd
        - beliefs/overconfidence.qmd
        - beliefs/beliefs-exercises.qmd
    - part: game-theory/game-theory.qmd
      chapters:
        - game-theory/simultaneous-move-one-shot-games.qmd
        - game-theory/sequential-games.qmd
        - game-theory/asymmetric-information.qmd
        - game-theory/strategic-moves-and-commitment.qmd
        - game-theory/game-theory-exercises.qmd
    - part: behavioural-game-theory/behavioural-game-theory.qmd
      chapters:
        - behavioural-game-theory/level-k-thinking.qmd
        - behavioural-game-theory/asymmetric-information.qmd
        - behavioural-game-theory/emotions.qmd
        - behavioural-game-theory/behavioural-game-theory-exercises.qmd
    - part: social-preferences/social-preferences.qmd
      chapters:
        - social-preferences/distribution.qmd
        - social-preferences/reputation.qmd
        - social-preferences/reciprocity.qmd
        - social-preferences/social-preferences-examples.qmd
        - social-preferences/social-preferences-exercises.qmd
    - references.qmd
  navbar:
    background: primary
    search: true
    right:
      - text: "PDF version"
        href: https://behaviouraleconomics.jasoncollins.blog/Notes-on-behavioural-economics.pdf
      - text: "Blog"
        href: https://www.jasoncollins.blog/
      - text: "About"
        href: https://www.jasoncollins.blog/about/
      - icon: twitter
        href: https://twitter.com/jasonacollins
  sidebar:
    collapse-level: 1
  repo-url: https://github.com/jasonacollins/behaviouraleconomics
  repo-actions: [issue]
  page-footer: 
    center:
      - text: "Copyright: CC-BY"
        href: https://creativecommons.org/licenses/by/4.0/
      - icon: twitter 
        href: https://twitter.com/jasonacollins
  open-graph: true
  twitter-card: true

bibliography: references.bib
csl: apa-no-ampersand.csl

format:
  html:
    theme: cosmo
    fontcolor: black
    fontsize: 20px
    linkcolor: blue
    css: styles.css
    html-math-method: katex
    link-external-newwindow: true
    code-fold: true
    fig-cap-location: top
  pdf:
    documentclass: report
    echo: false
    toc-depth: 1
    fig-width: 6
    fig-height: 4

filters:
  - lightbox
lightbox: auto

execute:
  freeze: auto
  keep-md: false
  fig-pos: 'H'
  
editor: source
