# Loss aversion

Loss aversion can instead explain why we behave differently depending on whether the decision making induces a gain or a loss. Loss aversion is the concept that losses loom larger than gains.

People feel more strongly about a loss than they do an equivalent gain, so are often willing to reject gambles with a materially positive expected value.

For instance, if someone feels losses with twice the feeling of gains, a 50:50 bet to win \$550, lose \$500 will be unattractive. This provides an alternative explanation to the absurd levels of risk aversion required to reject this bet (as discussed in @sec-absurd).

## Loss aversion in a deterministic environment: the endowment effect

@kahneman1991 ran one of the most famous and replicated experiments in economics.

They randomly assigned a free mug to members of a group and asked how much money they would accept for returning the mug (i.e. willingness to accept). The remaining participants were only shown a mug and asked their willingness to pay for the mug.

@kahneman1991 found that the willingness to accept (\$5.75) was substantially higher than the willingness to pay (\$2.25).

This experiment has been replicated in real estate markets, the stock market, with basketball tickets and in other domains. 

The endowment effect is this phenomena where people impute additional value to the items they own. The endowment effect is argued to be an empirical expression of loss aversion. Willingness to accept is higher as it is payment to incur the loss of the mug.

## Loss aversion in the value function

The following is an example of a value function with reference dependence and loss aversion:

$$
v(x)=\left\{\begin{matrix}
x \space &\textrm{where} \space x \geq 0\\
2x \space &\textrm{where} \space x<0
\end{matrix}\right.
$$

Where $x$ is the outcome relative to the reference point.

For example, suppose someone is given \$100. If their initial reference point is their  wealth before receiving the \$100, $x$ will be \$100. Therefore their utility is +100. If the same person instead loses \$100, their utility would be -200.
