# Sophisticated present bias

## Naïve and sophisticated present-biased agents

A naive present-biased agent discounts all future periods but incorrectly believes that they do not have this problem in the future.

A sophisticated present-biased agent discounts all future periods and correctly believes that they will have this problem also in the future. They understand that if faced with the temptation to take benefits today or delay costs, they will do so.

A sophisticated and naive person can make different decisions despite having the same level of impatience, $\delta$, and the same level of present bias, $\beta$.

The naive agent makes its plans by forward reasoning, starting from today.

1. Solve for the optimal action given the possible futures, believing they will stick to the plan once they move to next period.

2. Move to next time period ($t+1$)

3. Recompute their optimal plan, believing they will stick to the plan once they move to next period.

4. Iterate

The sophisticated agent makes its plans by backward reasoning, starting from the final time period.

1. Solve for the optimal action

2. Go back one time period and solve for preferred action, accounting for the decision in (1)

3. Iterate

## Examples

### Example 1

Suppose we have a naive and a sophisticated present-biased agent, each with $\delta=0.95$, $\beta=0.95$ and utility each period of $U(x_n)=x_n$.

We offer them the following choice.

> Would you like \$100 next week or \$110 in two weeks? 

We also tell them that we will give them the opportunity to reconsider their decision next week.

The present-based agent that we examined in the earlier example was naïve. They did not realise that they would change their mind if offered that opportunity after a week. They would be surprised by that change.

When making their initial decision, the comparison they are making from the perspective of today is simply between the discounted utilities from the perspective of today:

$$U_0(1,\$100)=90.25$$

$$U_0(2,\$110)=94.32$$

But this is an incorrect view as to their preferences next week. Next week they will calculate utility as:

$$U_1(1,\$100)=100$$

$$U_1(2,\$100)=99.275$$

Today they hold an incorrect belief as to what their preference will be next week .

The sophisticated agent will first consider how they will look at the choice next week:

$$U_1(1,\$1001)=100$$

$$U_1(2,\$110)=99.275$$

The sophisticated agent sees that next week they will take the \$100.

As a result, today the sophisticated agent will choose \$100 in one week. They see their future decision and know that \$110 in two weeks is not available to them. They effectively accept their future present bias now.

In this example, being naive or sophisticated does not change their final decision. It only changes their beliefs about their final decision before they reach it.

### Example 2

Suppose we have a naive and a sophisticated present-biased agent, each with $\delta=1$, $\beta=0.5$ and utility each period of $U(x_n)=x_n$. They are present-biased, but beyond that present-bias demonstrate no impatience.

We offer them the following choice.

- \$6 today ($t=0$)

- \$10 in one week ($t=1$)

- \$16 in two weeks ($t=2$)

They are also told that next week they will be offered an opportunity to change their mind.

[Note: I am using $ for many of these examples, but these could equally be many other things: e.g. three movies that each provide 6, 10 or 16 utility and you can only afford to attend one.]

First, we consider the naive agent. They calculate utility from the perspective of today. 

\begin{align*}
U_0(0,\$6)&=u(\$6) \\
&=6
\end{align*}

\begin{align*}
U_0(1,\$10)&=\beta\delta u(\$10) \\
&=0.5*1*10 \\
&=5
\end{align*}

\begin{align*}
U_0(2,\$16)&=\beta\delta^2 u(\$16) \\
&=0.5*1^2*16 \\
&=8
\end{align*}

The naive agent will choose the \$16 in two weeks.

But what then happens when the naive agent is given the chance to change their mind after one week. 

\begin{align*}
U_1(\$10 \text{ at }t=1)&=u(\$10) \\
&=10
\end{align*}

\begin{align*}
U_1(\$16 \text{ at }t=2)&=\beta\delta u(\$16) \\
&=0.5*1*16 \\
&=8
\end{align*}

The naive agent will change their mind and take the \$10.

What of our sophisticated agent? They will make their decision today based on their correct beliefs about their future preferences. To do this, they solve by backward induction. First, what will their decision be next week?

\begin{align*}
U_1(1,\$10)&=u(\$10) \\
&=10
\end{align*}

\begin{align*}
U_1(2,\$16)&=\beta\delta u(\$16) \\
&=0.5*1*16 \\
&=8
\end{align*}

The sophisticated agent can see that they will choose to receive \$10 immediately when asked next week.

Knowing this is the case, the sophisticated agent now decides whether they prefer the \$6 today or the \$10 next week. 

\begin{align*}
U_0(0,\$6)&=u(\$6) \\
&=6
\end{align*}

\begin{align*}
U_0(1,\$10)&=\beta\delta u(\$10) \\
&=0.5*1*10 \\
&=5
\end{align*}

They prefer the $6 today.

The result is that the sophisticated agent will choose the \$6 today. From today’s perspective, they would prefer the \$16 in two weeks, but as they know they will cave in to their present bias next week and take the \$10, they make today’s decision on that basis.

### Example 3

A naive present-biased agent has failed to return their library books and is fined at at $t=0$. They can select one of the following payment schemes:

$(0,-\$10)$, $(1,-\$15)$ or $(2,-\$25)$

That is, they can pay \$10 today, \$15 at $t=1$ or \$25 at $t=2$.

They are free to change the scheme over time as they see fit.

The agent’s utility is linear in money $U(x_n)=x_n$, with discount factors $\delta=1$ and $\beta=0.5$.

We start calculating utility from today:

\begin{align*}
U_0(0,-\$10)&=u(-\$10) \\
&=-10
\end{align*}

\begin{align*}
U_0(1,-\$15)&=\beta\delta u(-\$15) \\
&=0.5*1*(-15) \\
&=-7.5
\end{align*}

\begin{align*}
U_0(2,-\$25)&=\beta\delta^2 u(-\$25) \\
&=0.5*1^2*(-25) \\
&=-12.5
\end{align*}

The naive agent will choose to pay \$15 at $t=1$.

Now we move to $t=1$, when the naive agent reconsiders their decision:

\begin{align*}
U_1(1,-\$15)&=u(-\$15) \\
&=-15
\end{align*}

\begin{align*}
U_1(2,-\$25)&=\beta\delta u(-\$25) \\
&=0.5*1*(-25) \\
&=-12.5
\end{align*}

The naive agent will choose to change their decision and further delay their payment. They will now choose to pay \$25 at $t=2$.

When they reach $t=2$, they have no choice but to pay the \$25.

A sophisticated present-biased agent has failed to return their library books and is fined at t =0. They can select one of the following payment schemes:

$(0,-\$10)$, $(1,-\$15)$ or $(2,-\$25)$

That is, they can pay \$10 today, \$15 at $t=1$ or \$25 at $t=2$.

They are free to change the scheme over time as they see fit.

The agent’s utility is linear in money $U(x_n)=x_n$, with discount factors $\delta=1$ and $\beta=0.5$.

For the sophisticated agent, we start calculating utility from the final period.

At $t=2$, they have no choice but to pay the $25.

What of $t=1$?

\begin{align*}
U_1(1,-\$15)&=u(-\$15) \\
&=-15
\end{align*}

\begin{align*}
U_1(2,-\$25)&=\beta\delta u(-\$25) \\
&=0.5*1*(-25) \\
&=-12.5
\end{align*}

The sophisticated agent can see that if they make a choice at $t=1$, they will choose to pay $25 at t = 2.

Now we iterate at t = 0. The sophisticated agent only compares \$10 at $t=0$ with \$25 at $t=2$ because they know that at $t=1$ they will select \$25 at $t=2$. They know that if they delay once they will delay again and end up paying the largest fine. Hence they limit their comparison to those outcomes that might occur:

\begin{align*}
U_0(0,-\$10)&=u(-\$10) \\
&=-10
\end{align*}

\begin{align*}
U_0(2,-\$25)&=\beta\delta^2 u(-\$25) \\
&=0.5*1^2*(-25) \\
&=-12.5
\end{align*}

As $U_0(0,-\$10)>U_0(2,-\$25)$, the sophisticated agent will choose to pay \$10 at $t=0$.

In our examples we have seen two contrasting outcomes for the sophisticated agent.

In one example they took \$6 today (rather than \$10 in one week or \$16 in two) because they knew that they would take the $10 in one week. They took the lowest possible outcome.

In the latest example, they paid the lowest possible fine as they saw they would further delay paying the fine in the future, leading it to increase even more.

Suboptimality of sophisticated behaviour arises from two tensions:

1. They understand that they will not be able to wait for the optimal time.

2. They are present-biased so prefer benefit today and costs delayed to the future.

In combination, these imply a sophisticated agent will generally take action earlier than the naive agent. They can “prepoperate”, which is doing something now when it would be better to wait.
