# What is behavioural economics? {.unnumbered}

Behavioural economics is a discipline that seeks to increase the explanatory power of traditional economic approaches by incorporating more realistic psychological foundations.

Behavioural economics retains the general framework and tools used by economists, such as utility maximisation, but deviates from some assumptions to generate new insights and better predictions. These deviations are generally grounded in observed behaviour rather than abstract principles.

As behavioural economics revisits our fundamental understanding of economic behaviour, it has implications for all areas of economics.

## What is not behavioural economics?

The term "behavioural economics" is commonly used to describe work that is better described as psychology or "behavioural science".

Economics is the study of how economic agents make decisions under conditions of scarcity and of the interactions between those agents.

Behavioural science is the study of human behaviour. Behavioural economics is not just about studying human behaviour, but about how a better understanding of human behaviour could improve the study of the decisions of economic agents and their interactions.

Similarly, psychology is the study of the human mind, decisions and behaviour. It is part of the behavioural sciences. Psychology is broad with many discrete fields. Behavioural economics tends to draw on a small subset of psychological research in refining the economic view on human behaviour.

## Three thought experiments

Many early behavioural economics experiments were built on thought experiments concerning human behaviour that was hard to explain with traditional economic frameworks.

Below are three thought experiments to illustrate the types of problems that concern behavioural economists. In this book I will examine potential explanations for each of these behaviours.

### Thought experiment 1

This first thought experiment comes from @kahneman1984.

A. Imagine that you have decided to see a play and paid the admission price of \$100 per ticket. As you enter the theatre, you discover that you have lost the ticket. The seat was not marked, and the ticket cannot be recovered.

Would you pay \$100 for another ticket?

B. Imagine that you have decided to see a play where admission is \$100 per ticket. As you enter the theatre, you discover that you have lost a \$100 bill.

Would you still pay \$100 for a ticket for the play?

The two situations appear equivalent, yet people are more likely to pay \$100 for a ticket in scenario B.

### Thought experiment 2

This second thought experiment comes from @thaler1980.

Mr. R bought a case of good wine ... for about \$5 a bottle. A few years later his wine merchant offered to buy the wine back for \$100 a bottle. He refused, although he has never paid more than \$35 for a bottle of wine.

Why is there such a large difference between the price at which he is willing to buy and the price at which he is willing to sell?

### Thought experiment 3

This third thought experiment also comes from @thaler1980.

A group of hungry economists is awaiting dinner when a large can of cashews is opened and placed on the coffee table. After half the can is devoured in three minutes, everyone agrees to put the rest of the cashews into the pantry.

Why did they agree to remove the cashews when they simply could have not eaten them? Why did they deliberately reduce their choice set?
