# Game theory

## Summary {.unnumbered}

- Game theory studies strategic interactions between players, where each player's outcome depends on the behaviour of others, and strategies depend on beliefs about others' strategies.
- The components of a game include: players, actions, strategies, information, and payoffs. Players are typically assumed to be rational optimisers who understand the game and assume others are rational optimizers as well.
- Games can be classified into different types, such as cooperative vs. non-cooperative games. In cooperative games, players can negotiate binding contracts, while in non-cooperative games, they cannot.
- Games can also be simultaneous or sequential. In simultaneous games, players make decisions without knowing others' actions, while in sequential games, players make decisions knowing the previous actions of other players.

---

::: {.content-visible when-format="html"}

{{< video https://youtu.be/zZ8iIMpTBJs >}}

---

:::

## Introduction

In many situations, your outcome depends on others’ behaviour. Their outcome depends on your behaviour.

Similarly, your strategy will depend on your belief about others’ strategy. Their strategy depends on their beliefs about your strategy.

Game theory studies this strategic interaction between players. We can solve strategic problems using the tools of game theory.

## Components of a game

A game has the following components:

- First, the **players** of the game. Most of the games we examine in these notes involve two players.

- Second, the **actions** that each player can take; for example to contribute to a common pool or to defect.

- Third, the **strategies** that comprise a complete contingent plan of action. That is, for any given scenario or action by another player, a strategy specifies the action to be taken by the player.

- Fourth, the **information** available to players. In these notes, we generally assume perfect information.

- And finally, the **payoffs**. This comprises a complete summary of the value to each player of each set of actions.

## The players

In game theoretical analysis, we typically assume that the players are rational optimisers who understand the game that they are playing. By rational, we mean that the player is aware of their alternatives, forms expectations about any unknowns, has preferences that conform to the axioms of completeness and transitivity and they choose the best option using some optimisation algorithm.

We also assume that the players assume other players are also rational optimisers who understand the game.

We weaken this assumption when we analyse behavioural game theory.

## Types of games

There are many different types of games analysed in game theory. Some of the delineations between these games are as follows.

### Cooperative versus non-cooperative games

First, games are often divided into cooperative and non-cooperative games.

In non-cooperative games, players are not allowed to negotiate binding contracts. In cooperative games, players can negotiate binding contracts that allow them to implement joint strategies.

In these notes, I will focus on non-cooperative games.

### Simultaneous or sequential games

Second, games can involve simultaneous or sequential moves.

In a simultaneous move game, you make decisions without knowing the action of your rival.

In sequential games, players make sequential decisions knowing the other player's action.
We will examine both of these types of game in these notes.