# Delayed gratification, spread and variation

Recall the assumption of utility independence:

> All that matters is maximising the sum of discounted utilities. Decision-makers are assumed to have no preference for the distribution of utilities.

However, there is evidence that people care about the shape of the utility stream over time. There is evidence that people delay gratification, and prefer spread and variation. They don’t care solely about maximising discounted utility. 

This evidence suggests that the assumption of utility independence does not hold. I will now discuss these three bodies of evidence.

## Delayed gratification

The first concerns delayed gratification.

Consider the following example:

> It is a sunny weekend. You can either study today and go to the beach tomorrow, or you can go to the beach today and study tomorrow.
> 
> Studying gives you a utility of 10. Going to the beach gives you a utility of 20.

What would an exponential discounter with $\delta=0.8$ do?

What would a present-biased agent with $\beta=0.5$ and $\delta=0.8$ do?

Both agents would go to the beach today and study tomorrow. They will always schedule pleasant tasks before unpleasant tasks.

Does this match people’s observed behaviour?

There is considerable evidence that people will schedule unpleasant tasks first and pleasant ones later. This might be thought of as a preference for an increasing utility profile.

How could this be possible for someone who discounts the future?

One way is to ease the requirement that $\delta$ be less than one. This provides a solution to the weekend problem but also leads to the potential of endlessly postponing pleasant experiences.

Easing this requirement also clashes with other evidence that people often postpone unpleasant tasks and that people have a $\delta$ much less than one for many decisions.

## Spread of utility

Another body of evidence suggests that we prefer a spread of utility. We like to distribute pleasant experiences over time.

In part, this emerges from diminishing marginal utility. Additional units of a good or service on a day when we already have ample will provide less utility than on a day when we have little.

However, some of the evidence cannot be accounted for by diminishing marginal utility.

For example, suppose someone plans to catch up with one friend over lunch and another at dinner. Some people prefer these two events on different days, giving them a spread of utility over time.

## Variation

We also have a preference for variation. Consider the following:

>Your favourite meal is lasagna. Your second favourite meal is spaghetti bolognese. Your third favourite is fish and chips.
>
>You are offered the following two options:
>
>1. Lasagna every night for the next week.
>2. Alternating meals of lasagna, spaghetti and fish and chips.

We don’t choose to have the same good or service over and over.
