# Asymmetric information

We saw earlier in our examination of the market for lemons and the winner's curse that asymmetric information can cause market failures even if agents are fully rational.

When we mix psychology and asymmetric information:

-   People under-estimate the extent to which informational differences drive others' behaviour. They often act as if others have the same information set that they do

-   Better informed agents can fail to take advantage of their informational advantage against less informed agents because they don't understand the link between information and behaviour.

We will examine a phenomenon, the curse of knowledge, where agents with a different information set under-appreciate the extent to which others' strategies depend on that information.

## The curse of knowledge

The idea behind the curse of knowledge is that better informed agents should ignore the additional information they hold when predicting the actions of less-informed agents. Experimental evidence shows that people are unable to ignore their private information even when it is in their interests to do so.

For example, @newton1990 had students participated in an experiment in one of two roles: "Tapper" and "Listener".

Tappers received a list of 25 well-known songs and were asked to "tap out" the rhythm of one of the songs.

Listeners tried to identify the song based solely on the taps.

Tappers predicted that listeners would identify 50% of the songs.

Listeners only identified 3 of 120 songs correctly (a rate of about 2.5%).

## Cursed equilibrium

@eyster2005 developed a model of "cursed equilibrium".

A cursed player underestimates the extent to which another player's behaviour depends on that player's private information.

In the extreme case a fully-cursed player thinks the other player's behaviour doesn't depend on their private information at all. A fully-cursed player understands that the other player might do different things (e.g. bid high or low), but thinks that this is independent of their private information.

They propose "cursed equilibrium", where each player correctly anticipates the distribution of play by others and maximizes utility given their (cursed) beliefs.

That is, cursed players do not fully take into account the correlation between the actions of other players and their types. Instead, cursed players believe their opponent plays the average optimal action, not the type-contingent action.

### The market for lemons

In the lemon market, a cursed buyer doesn’t think that the seller’s decision of whether to say yes to the trade depends on the seller’ evaluation of the car.

Return to our market for lemons and suppose that $q=0.2$. That is, only 20% of the cars are good. Under the parameters we explored, only lemons are sold.

Rather than considering that the 20% of good car owners are willing to sell their car with 0% probability and the 80% of lemon owners are willing to sell with 100% probability, the cursed players might average over the two types and consider each type has an 80% chance to sell.

Under that miscalculation they are willing to pay up to the (mistakenly) expected value of:

$$
E=0.8×15000+0.2×7500=13500
$$

They would be willing to pay up to \$13,500 despite the market comprising only lemons (valued at only \$7,500 by buyers).

## The winner's curse

Consider now our example of the winner’s curse and bidding for an oil field.

Assume Player 1 is fully cursed and therefore assumes Player 2’s bid is independent of $v_2$. Player 1 assumes $v_2$ is on average $50 and that Player 2 bids half of the time regardless of $v_2$.

Company 1’s expected profit if they bid $v_1$ is:

\begin{align*}
\hat E[\pi_1|\text{bid }v_1]&=\frac{1}{2}\pi_1(2\text{ no bid}|v_2=50)+\frac{1}{2}\bigg(\frac{1}{2}\pi_1(\text{lose}|v_2=50)+\frac{1}{2}\pi_1(\text{win}|v_2=50)\bigg) \\
&=\frac{1}{2}\bigg(\frac{v_1+50}{2}-v_1\bigg)+\frac{1}{4}\times 0+\frac{1}{4}\bigg(\frac{v_1+50}{2}-v_1\bigg) \\
&=\frac{3}{4}(25-\frac{v_1}{2})
\end{align*}

We can see that:

$$
\hat E[\pi_1|\text{bid}]>0 \Leftrightarrow v_1>50
$$

However, as shown previously, this bidding approach leads to an expected loss.

In general, the cursed bidder under-appreciates that another bidder is more likely not to bid when that other bidder’s information is bad. Therefore, they under-appreciate the extent to which winning the auction is bad news.
