# Probability theory

::: {.content-visible when-format="html"}

{{< video https://youtu.be/Ceor2U7Fy3Q >}}

---

:::

Consider the following judgments:

- An investor picking which stock or fund they should invest in

- A surgeon deciding whether an operation would result in a good outcome for the patient

- You considering how much you need to save to have a good retirement

- A judgment as to whether your friend is bluffing or genuinely has a strong poker hand.

These judgments involve risk (the probabilities are known) or uncertainty (the probabilities are unknown). We do not know all elements of the current state of the world and the probability that we are in any particular state. We do not know what will happen in the future and the probability with which each state occurs.

To analyse decision-making under risk and uncertainty, we need to consider how people form beliefs and compute probabilities in any decision. I will do this first by examining the foundations of probability theory.