# Expected value

## Summary {.unnumbered}

- The expected value of a gamble is the average outcome in the long run, calculated as the probability-weighted sum of potential outcomes.
- For a gamble with $n$ possible outcomes $x_i$, each occuring the probability $p_i$, the expected value is expressed as:

\begin{align*}
\mathbb{E}[X]&= p_1x_1 + p_2x_2 + ... + p_nx_n \\[6pt]
&=\sum_{i=1}^n p_ix_i
\end{align*}

---

::: {.content-visible when-format="html"}

{{< video https://youtu.be/S1xWVbEDiTY >}}

---

:::

## Introduction

The expected value of a gamble is the amount you can expect to win on average, in the long run, when you play a gamble.

Suppose I offer to flip a coin. I give you \$1 if it is heads and you will give me \$1 if it is tails. What is the expected value of this gamble?

The expected value is \$0. You lose \$1 half the time and gain \$1 half the time.

Formally, given a gamble, the expected value $E[X]$ of the random variable $X$ is the probability-weighted sum of the potential outcomes. That is, we calculate the expected value by multiplying each possible outcome by the probability with which it occurs.

For the coin flip example, you multiply the 50% probability of heads by the \$1 outcome and the 50% probability of tails by the -\$1 outcome.

| Probability | Outcome |
|:-----------:|:-------:|
|     50%     |  +\$1   |
|     50%     |  -\$1   |

$$
E[X]=0.5 \times 1 + 0.5 \times (-1) = 0
$$

We calculate the expected value of a gamble with $n$ possible outcomes using the following equation:

```{=tex}
\begin{align*}
E[X]&=p_1x_1+p_2x_2+...+p_nx_n \\[6pt]
&=\sum_{i=1}^np_ix_i
\end{align*}
```
In this equation, $p_i$ is the probability of outcome $x_i$.

For those unfamiliar with the mathematical notation in the second line, the large symbol sigma allows us to write what could be a long expression much more succinctly. It means that we sum the term $p_ix_i$ for each value of $i$ for 1 through to $n$. We sum $p_1x_1$ with $p_2x_2$ and so on until we reach $p_nx_n$. Breaking it down this way shows that the second line is equivalent to what I wrote in the first line.

## Expected value examples

I will now illustrate the concept of expected value with some simple examples.

### Example 1

You are offered a bet with a 50% chance of winning \$10 and a 50% chance of losing \$8.

The expected value of the gamble $X$ is:

```{=tex}
\begin{align*}
E[X]&=\sum_{i=1}^n p_ix_i \\[12pt]
&=0.5\times 10+0.5\times (-8) \\[6pt]
&=\$1
\end{align*}
```
Relating back to my earlier explanation of the summation symbol, here we have $n=2$ outcomes. We sum $p_1=0.5$ multiplied by $x_1=10$ with $p_2=0.5$ multiplied by $x_2=-8$.

Suppose your chance of winning increases to 60%. The expected value of the gamble is:

```{=tex}
\begin{align*}
E[X]&=\sum_{i=1}^n p_ix_i \\[12pt]
&=0.6\times 10+0.4\times (-8) \\[6pt]
&=\$2.80
\end{align*}
```
### Example 2

You are offered a bet with a 50% chance of winning 50% of your wealth and a 50% chance of losing 40% of your wealth.

The expected value of the bet is:

```{=tex}
\begin{align*}
E[X]&=\sum_{i=1}^n p_ix_i \\[12pt]
&=0.5\times 0.5W+0.5\times (-0.4W) \\[6pt]
&=0.05W
\end{align*}
```
The expected value is 5% of your wealth.