# Economic foundation exercises

## Buridan's ass

The paradox of Buridan's ass runs as follows: An ass that is equally hungry and thirsty is placed halfway between a pile of hay and a bucket of water. The ass cannot decide between the hay and water, so dies of dehydration and starvation.

What axioms of choice are relevant to this fable? Are any axioms violated?

::: {.callout-tip collapse="true"}
## Answer

The axiom of completeness is violated. Under this axiom an agent cannot fail to have a preference between two options (although that preference may be indifference).

Incompleteness is different from indifference. Is the ass was merely indifferent it would be happy taking either option and be equally satisfied. Indifference does not make a choice impossible.
:::

## Picking a mobile plan

You are considering two mobile phone plans. Each has different monthly fees, data caps, excess data charges, international inclusions and 5G coverage. You realise it will take all day to work through the fine print to understand the plans.

You decide that your options are:

- Pick a plan by flipping a coin.
- Spend the day working through the plans and choose one.
- Avoid the work by reading a book instead.

Does this decision accord with the axioms we have discussed?

::: {.callout-tip collapse="true"}
## Answer

All three choices could be considered to accord with the axioms we have discussed. What we have effectively done in each case is created a richer choice set. In no case are their preferences incomplete. You could think of the choice set as {Plan A, Plan B, invest to understand plans, do something else}.

You would only state that the preferences are incomplete if the agent wasn't able to express a preference between Plan A and Plan B. However, if they were forced to choose and happy to flip a coin, that would suggest indifference.
:::

## Rationality

Consider the following statements about rationality in economics. How do these criticisms relate to the definition of rationality we have discussed?

a\) From [Robert Frank in the New York Times](https://www.nytimes.com/2008/02/10/business/10view.html):

> TRADITIONAL economic models assume that people are self-interested in the narrow sense. If “homo economicus” - the stereotypical rational actor in these models - finds a wallet on the sidewalk, he keeps the cash inside. He doesn’t leave tips after dining in restaurants that he will never visit again. And he would never vote in a presidential election, much less make an anonymous donation of money or time to a presidential campaign.

::: {.callout-tip collapse="true"}
## Answer

The traditional economic axioms assume self-interest in a narrow sense, in that people make decisions in accordance with their preferences. However, completeness and transitivity say nothing about the content of those preferences. A person might prefer to return the wallet or leave a large tip for the good feeling they get. They might enjoy voting and care about outcomes for others.

Even auxiliary axioms such as monotonicity or non-satiation leave these possibilities open in that while the agent will always want more, they do not require that it is purely for their own benefit.
:::

b\) From [Brian Easton in interest.co.nz](https://www.interest.co.nz/public-policy/116603/economist-brian-easton-says-behavioural-economics-challenges-our-assumptions):

>For the last 150 years much economic analysis has been based on homo economicus, an ‘economic’ man who is rational and narrowly self-interested and who pursues his subjectively defined ends optimally.

::: {.callout-tip collapse="true"}
## Answer

First, "man who is rational" accords with the technical definition in economics but differs from how used in common speech (and likely that of readers of the article).

If we read "narrowly self-interested" to mean that they make decisions in accordance with their preferences, then we might agree with that statement. However, we cannot place any further content into that idea of self-interest.

Similarly, the statement "pursues his subjectively defined ends optimally" accords with the idea that under the axioms of completeness and transitivity, the consumer behaves as if they have a utility function $U(x_i)$ over outcomes $x_i$. They are able to choose between any two options. They also do not make errors (although randomness can be built into utility functions). This definition of "optimally" is narrower than might be used in common speech.
:::

## Apples and oranges

Elmer claims he has no preference between apples and oranges and is genuinely indifferent between the two. Is this stance consistent with the completeness axiom? Explain why or why not. (2 marks) [200 word limit.]

::: {.callout-tip collapse="true"}
## Answer

Elmer's stance of being indifferent between apples and oranges is consistent with the completeness axiom.

The completeness axiom states that for any two options A and B, an individual can always specify exactly one of these three possibilities: A is preferred to B, B is preferred to A, or the individual is indifferent between A and B.

Elmer's claim of indifference between apples and oranges satisfies this axiom. He has a clear preference relation between the two options (indifference), which is one of the three possibilities allowed by the completeness axiom.

:::

## Small or medium coffee?

Sam's local cafe offers two sizes of coffee: small and regular. Each day, Sam orders a small coffee.

The cafe then introduces a new large size. Sam starts ordering the regular.

What axiom is Sam violating? Explain. (2 marks) [200 word limit]

::: {.callout-tip collapse="true"}
## Answer

Sam's action is inconsistent with the independence of irrelevant alternatives.

Under the independence of irrelevant alternatives, if A is preferred to B, then this preference should remain unchanged in the presence of a third option C. 

Initially, Sam prefers small to regular. After the introduction of the large size, Sam switches to preferring regular to small. This change in preference between small and regular, triggered solely by the presence of the large option (which Sam doesn't even choose), contradicts the axiom.

This scenario does not involve probabilities, as the independence axiom is defined, so we can't evaluate it in terms of the independence axiom.

:::