# The reflection effect

The reflection effect involves an asymmetry in risk preferences in the gain and loss domains.

When people make a risky choice related to gains, they are risk averse. They prefer a certain option with lower expected utility than the expected utility of the risky choice. When choosing an option in the loss domain, they become risk-seeking. This phenomenon is called the reflection effect.

The reflection effect might also be thought of as diminishing sensitivity to gains or losses in either direction. This contrasts with expected utility theory where the pain of losses increases as they grow in size.

The reflection effect explains the framing effects in the following experiment by @kahneman1984.

One group of experimental subjects were asked the following.

> Imagine that the U.S. is preparing for the outbreak of an unusual Asian disease, which is expected to kill 600 people. Two alternative programs to combat the disease have been proposed. Assume that the exact scientific estimates of the consequences of the programs are as follows:
>
> If Program A is adopted, 200 people will be saved.
>
> If Program B is adopted, there is a one-third probability that 600 people will be saved and a two-thirds probability that no people will be saved.
>
> Which of the two programs would you favour?

72% of participants chose option A.

Another group of experimental participants were shown the following:

> Imagine that the U.S. is preparing for the outbreak of an unusual Asian disease, which is expected to kill 600 people. Two alternative programs to combat the disease have been proposed. Assume that the exact scientific estimates of the consequences of the programs are as follows:
>
> If Program C is adopted, 400 people will die.
>
> If Program D is adopted, there is a one-third probability that nobody will die and a two-thirds probability that 600 people will die.
>
> Which of the two programs would you favour?

22% of participants chose option C.

72% of participants chose A and 22% of participants chose option C. Yet these two are equivalent. Option A and B are in the gain domain. Therefore the less risky option A is preferred. Options C and D are in the loss domain. Therefore the more risky option C is preferred.

## The reflection effect in the value function

The following value function is an example of a function where there is diminishing sensitivity to both gains and losses. This function can generate the reflection effect.

\begin{equation*}
v(x)= \Bigg\{
\begin{matrix}
x^\frac{1}{2} \space \text{where} \space x \geq 0\\
-(-x)^\frac{1}{2} \space \text{where} \space x<0
\end{matrix}
\end{equation*}

As $x$ increases in magnitude in either direction, the marginal increase in value from each incremental unit of $x$ decreases.

The result of this value function is risk-averse behaviour in the gain domain and risk-seeking behaviour in the loss domain. The following plot shows the diminishing effect in each direction.

```{r}
library(ggplot2)

loss_fun <- function(x){
  -(-x)^0.5
}
gain_fun <- function(x){
  x^0.5
}

loss <- data.frame(
  x=seq(-10,0,0.05),
  y=NA
  )
loss$y <- loss_fun(loss$x)

gain <- data.frame(
  x=seq(0,10,0.05),
  y=NA
  )
gain$y <- gain_fun(gain$x)

ggplot(mapping = aes(x, y)) +
  geom_line(data = loss) +
  geom_line(data = gain) + 
  geom_vline(xintercept = 0, linewidth=0.25)+ 
  geom_hline(yintercept = 0, linewidth=0.25)+
  labs(x = "", y = "V(X)")
```

In the gain domain, the function is convex, indicating risk aversion. In the loss domain, the concave function indicates risk-seeking behaviour.

The following numerical example illustrates further.

Suppose an agent with the above value function is offered a choice between \$10 for certain and a 50:50 bet to win \$20 or end up with nothing. The value of each choice is as follows.

\begin{align*}
v(\text{certainty})&=v(10) \\[6pt]
&=10^{\frac{1}{2}} \\[6pt]
&=`r round(10^0.5, 2)` \\
\\
v(\text{bet})&=0.5\times v(20)+0.5\times v(0) \\[6pt]
&=0.5\times 20^{\frac{1}{2}}+0.5\times 0 \\[6pt]
&=`r round(0.5*20^0.5, 2)`
\end{align*}

The $10 for certain has a higher value for the agent. This agent is risk averse in the gain domain and therefore prefers an amount for certain over a bet with the same expected value.

Suppose the agent is now offered another choice. They can now have a certain loss of \$10 or a 50:50 bet to lose \$20 or to lose nothing. The value of each choice is as follows.

\begin{align*}
v(\text{certainty})&=v(-10) \\[6pt]
&=-10^{\frac{1}{2}} \\[6pt]
&=`r round(-10^0.5, 2)` \\
\\
v(\text{bet})&=0.5\times v(-20)+0.5\times v(0) \\[6pt]
&=-0.5\times 20^{\frac{1}{2}}+0.5\times 0 \\[6pt]
&=`r round(-0.5*20^0.5, 2)`
\end{align*}

This bet delivers higher value than the certain loss, despite the bet and the certain loss having the same expected value. The agent is willing to take a risk to avoid a loss. They are risk seeking in the loss domain.
