# Distributional preferences



## Example: the trust game

In Tutorial 9 we considered whether Linda should invest in Marco's startup:

>Linda is looking for investment opportunities. She identifies a promising crypto-based start-up created by an Marco. Marco is looking for seed funding.
>
>Linda can invest \$10.
>
>If Linda invests, her investment will triple in value. Marco can then decide to either shut down the start-up and keep the \$30 or maintain the start-up in the market and pay a $15 dividend to each of Linda and himself.
>
>If Linda does not invest, Linda keeps the \$10. The start-up gets \$0.

We determined that Linda would not invest.

Suppose now that Linda and Marco have preferences as follows:

$$
U_L(x_L,x_M)=\left\{\begin{matrix}
\frac{1}{3}x_L+\frac{2}{3}x_M \quad &\textrm{if} \quad x_L \geq x_M\\[6pt]
\frac{2}{3}x_L+\frac{1}{3}x_M \quad &\textrm{if} \quad x_L < x_M 
\end{matrix}\right. \\
\\[12pt]
U_M(x_L,x_M)=\left\{\begin{matrix}
\frac{3}{4}x_L+\frac{1}{4   }x_M \quad &\textrm{if} \quad x_M \geq x_L\\[6pt]
x_M \quad &\textrm{if} \quad x_M < x_L 
\end{matrix}\right.
$$

Where $x_L$ and $x_M$ are the outcomes for Linda and Marco respectively.

Marco and Linda know each others utility functions.

What is the equilibrium with these distributional preferences? Explain the intuition.

If Linda chooses trust, Marco has a choice between \$15 each and \$30 for himself.

$$
U_M(x_L,x_M)=\left\{\begin{matrix}
\frac{3}{4}x_L+\frac{1}{4}x_M \quad &\textrm{if} \quad x_M \geq x_L\\[6pt]
x_M \quad &\textrm{if} \quad x_M < x_L 
\end{matrix}\right. \\
\\[12pt]
U_M(15,15)=\frac{3}{4}(15)+\frac{1}{4}(15)=15 \\
\\[12pt]
U_M(0,30)=\frac{3}{4}(0)+\frac{1}{4}(30)=7.5
$$

Marco receives higher utility by paying the dividend to Linda.

Linda also has utility from each distribution.

$$
U_L(x_L,x_M)=\left\{\begin{matrix}
\frac{1}{3}x_L+\frac{2}{3}x_M \quad &\textrm{if} \quad x_L \geq x_M\\[6pt]
\frac{2}{3}x_L+\frac{1}{3}x_M \quad &\textrm{if} \quad x_L < x_M 
\end{matrix}\right.\\
\\[12pt]
U_L(15,15)=\frac{1}{3}(15)+\frac{2}{3}(15)=15 \\
\\[12pt]
U_L(0,30)=\frac{2}{3}(0)+\frac{1}{3}(30)=10
$$

For the other node, if Linda does not invest, she will keep $10. Marco will have nothing.

\begin{align*}
U_M(10,0)=0 \\
\\
U_L(10,0)=\frac{1}{3}(10)+\frac{2}{3}(0)=3.33
\end{align*}

Putting those payoffs into the extensive form of the game, we get the following:



The new equilibrium is that Macro will return a dividend, so Linda invests.


